version: '3'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./public:/app/public
            - ../ssl:/etc/nginx/certs:ro
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 443:443
        depends_on:
            - php-fpm
        restart: always
    php-fpm:
        image: php:fpm-alpine
        volumes:
            - .:/app
        ports:
            - 9000:9000
        restart: always