version: "3"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./public:/app/public
      - ../ssl:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 443:443
    restart: always
